apiVersion: v1
kind: PersistentVolume
metadata:
  name: json-data-pv
  namespace: projetoadamod3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data-test  # Atualizado para o novo diretório
    type: Directory
