apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: projetoadamod3
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: projetoadamod3
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      tolerations:
      - key: "worker"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: minio
        image: quay.io/minio/minio
        args:
          - server
          - /data
          - --console-address
          - ":9001"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_PASSWORD
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: projetoadamod3
  name: minio
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: minio
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: minio-console
  selector:
    app: minio
