apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
  namespace: projetoadamod3
data:
  enabled_plugins: |
    [rabbitmq_management].
  rabbitmq.conf: |
    listeners.tcp.default = 5672
    management.listener.port = 15672
    management.listener.ssl = false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: projetoadamod3
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      tolerations:
      - key: "worker"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 15672 # Porta para o acesso à interface de gerenciamento
        - containerPort: 5672  # Porta padrão do RabbitMQ
---
apiVersion: v1
kind: Service
metadata:
  namespace: projetoadamod3
  name: rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: management
    port: 15672
    targetPort: 15672
    protocol: TCP
  - name: amqp
    port: 5672
    targetPort: 5672
    protocol: TCP