apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: projetoadamod3
type: Opaque
data:
  #guest
  RABBITMQ_ROOT_USER: Z3Vlc3Q= # Base64 encoded  
  RABBITMQ_ROOT_PASSWORD: Z3Vlc3Q= # Base64 encoded  