apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: projetoadamod3  # Especifica o namespace para o StatefulSet
  labels:
    app: redis
  name: redis
spec:
  serviceName: default
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      tolerations: # Permite que o pod seja agendado em nós com taints específicos
        - key: "worker" 
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - image: redis
          name: redis
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command:
                - "redis-cli"
                - "ping"
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - "redis-cli"
                - "ping"
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 1
            successThreshold: 0
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: projetoadamod3  # Especifica o namespace para o PVC
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: projetoadamod3  # Especifica o namespace para o Service
  labels:
    app: redis
  name: redis-svc
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis