apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: projetoadamod3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: robertosilvafelipe/worker:latest
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: REDIS_HOST
          value: "redis"
        - name: MINIO_URL
          value: "minio:9000"
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        - name: BUCKET_NAME
          value: "bucket-dadoscliente"